export const COUNTRIES: { code: string; name: string }[] = [
  { code: "AR", name: "Argentina" },
  { code: "BO", name: "Bolivia" },
  { code: "BR", name: "Brasil" },
  { code: "CL", name: "Chile" },
  { code: "CO", name: "Colombia" },
  { code: "CR", name: "Costa Rica" },
  { code: "CU", name: "Cuba" },
  { code: "EC", name: "Ecuador" },
  { code: "SV", name: "El Salvador" },
  { code: "GT", name: "Guatemala" },
  { code: "HN", name: "Honduras" },
  { code: "MX", name: "México" },
  { code: "NI", name: "Nicaragua" },
  { code: "PA", name: "Panamá" },
  { code: "PY", name: "Paraguay" },
  { code: "PE", name: "Perú" },
  { code: "DO", name: "República Dominicana" },
  { code: "UY", name: "Uruguay" },
  { code: "VE", name: "Venezuela" },
  { code: "US", name: "Estados Unidos" },
  { code: "ES", name: "España" },
  { code: "DE", name: "Alemania" },
  { code: "AU", name: "Australia" },
  { code: "CA", name: "Canadá" },
  { code: "CN", name: "China" },
  { code: "KR", name: "Corea del Sur" },
  { code: "FR", name: "Francia" },
  { code: "IN", name: "India" },
  { code: "IT", name: "Italia" },
  { code: "JP", name: "Japón" },
  { code: "MY", name: "Malasia" },
  { code: "NL", name: "Países Bajos" },
  { code: "PT", name: "Portugal" },
  { code: "GB", name: "Reino Unido" },
  { code: "RU", name: "Rusia" },
  { code: "SG", name: "Singapur" },
  { code: "CH", name: "Suiza" },
  { code: "TR", name: "Turquía" },
  { code: "AE", name: "Emiratos Árabes Unidos" },
];
